name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1.6.0
      with:
        dotnet-version: 3.1.x
        #source-url: https://nuget.pkg.github.com/ttkoma/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Add GITHUB package repository Source
      run: dotnet nuget update source github --source https://nuget.pkg.github.com/ttkoma/index.json --username ttkoma --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore -property:ContinuousIntegrationBuild=true
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal
    - name: Create Package
      run: dotnet pack -c Release --no-restore --no-build
    - name: Pubkish Package
      run: dotnet nuget push "**/bin/Release/*.nupkg" --source github #--skip-duplicate
    - name: Pubkish PackageSource
      run: dotnet nuget push "**/bin/Release/*.snupkg" --source github
